### ISSUE TITLE
Customize require search filter

### ISSUE THREAD

**Issue by MasterJames** [dylang/npm-check#292]
I do code loading differently and it says NOTUSED? it would be nice to set the pattern for custom matches

This loading reference I have hidden in a file that is itself loaded dynamically or from the command line as an extra argument to node. Like a file with different setting overrides for debugging, etc.

`lib.ipaddr = lib.require( 'ipaddr.js' );`

Is there a handy way to do that I missed? Maybe it's a suggestion then, because it's technically wrong for me.  Maybe your search filter needs modifying to find valid matches like this example given.

I do see I can and need to use --skip-unused as it's not right for virtual all packages.

`❤️  Your modules look amazing. Keep up the great work. ❤️`

**Comment by LinusU** [comment]
What is `lib` here? I think it would be hard to be able to detect that your function `lib.require(...)` uses the package, it could potentially do something else entirely as well?

Would you mind elaborating on your use case? :)

**Comment by MasterJames** [comment]
It's because every thing should have a place and I put require in lib where all things loaded with require also go. So it's a javascript object nothing more. It would be also be part of a single root branch much like a file system has a root. Further I use mostly 3 letter codes when possible not ironically similar to assembly. Lib has 3 letters. It's enough to uniquely identify 26^3 unique items. Anyway it is not an error as your thing says it is. If you feel that's not important or typical usage is your prerogative. I'm just saying. I gives a False negative in those kinds of situations not sure how or why it's just what I experienced.
I suppose one could have a customize value to say which objects contain the require function so it's not cluttering the global namespace. It could be a custom or different function for loading libraries named whatever, like rqr if in 3 letters. Food for thought I suppose. Take what you will and feel free to close this as you feel needed. Thanks for the helpful tool.

**Comment by LinusU** [comment]
> It's because every thing should have a place and I put require in lib where all things loaded with require also go. So it's a javascript object nothing more.

I'm just trying to figure out how this works, are you running under Node.js? Are are you in a different environment?

> Further I use mostly 3 letter codes when possible not ironically similar to assembly. Lib has 3 letters. It's enough to uniquely identify 26^3 unique items.

Totally off topic, but I would very much recommend against doing that. I think that this gives the gist of it: https://softwareengineering.stackexchange.com/a/33389/102283

> Anyway it is not an error as your thing says it is.

We haven't said it's an error, it's just that we don't detect that usage.

> If you feel that's not important or typical usage is your prerogative.

Since this is a very unusual setup, I don't think we want to make any changes to support this out of the box. Adding configuration to support could be on the table though.

> I gives a False negative in those kinds of situations not sure how or why it's just what I experienced.

It's because there is no way for us to know that `lib.require` loads other files. You could have named that function `lib.req` or even `lib.xyz`.

> I suppose one could have a customize value to say which objects contain the require function so it's not cluttering the global namespace. It could be a custom or different function for loading libraries named whatever, like rqr if in 3 letters.

Something like this could work, having a configuration for specifying the entire name.

> Take what you will and feel free to close this as you feel needed.

My personal recommendation, if you are on Node.js, would be to try and align with the rest of the eco-system. All files in Node.js are namespaced and kept separate, so there is already a "root" where your imported libraries will be.

Furthermore, Node.js and the JavaScript community at large is transitioning to using `import`/`export` instead of `require`. When this transition is done you won't be able to rename `require` since `import` is a language construct instead of a function.

> Thanks for the helpful tool.

Thanks!

**Comment by MasterJames** [comment]
As too short names it's just what works for me. Less to transmit is a reason not made in the link against.
Anyway I use node current versions. It's a bigger topic of reasoning as to why I do things the way I do and I'm not particularly influenced by what works best for other people. 
It's been a pleasure talking with you and appreciate you taking the time to understand the claim. 
Customizability option I suggested seems like an acceptable suggestion. I think others simply never bother to say anything and this might happen to more people then your aware of, then again it can be disabled so no biggy.
