### ISSUE TITLE
exitcode !== 0 on major updates

### ISSUE THREAD

**Issue by lippoliv** [dylang/npm-check#36]
Hey there,
for my CI Server it would be nice to add an Option "Exit Code 1 on Major up" so my Builds fail on Major updates...

Is that possible?

**Comment by dylang** [comment]
I would like this too, but help me understand the situation where you want your build to fail because of this check.

Major updates mean potential breaking changes. I'm not sure if that's you intend because incorporating the major update could be a significant undertaking, or even impossible if it requires a version of Node you are not ready to transition to.

Can you give an example of the scenario where you would expect your automatic build to fail?

**Comment by greensn0w** [comment]
@lippoliv: You could also use a bit ***Shell Magic*** ;)

```shell
if [[ $(npm-check) =~ '.*MAJOR.*' ]]; then; exit 1; fi;
```

**Comment by dylang** [comment]
I now exit with a non-zero code whenever there are updates. If you have ideas to make this more useful please let me know.

**Comment by borgogelli** [comment]
For CI it's a problem to have the exit code equals to 1. We would like to use npm-check only to give some info to the users and don't want to break our CI pipeline if there is a simple update of one package. The best solution would be the introduction of a new option like --ignore-update.
Regards
