### ISSUE TITLE
missing modules on node v4 

### ISSUE THREAD

**Issue by builtbylane** [dylang/npm-check#38]
I have node v4 installed using `n` (the node version manager), and npm-check is not finding any global packages other than npm itself. Morover, it's unable to update npm itself. everytime I re-run `npm-check -g -u` it tells me npm can be updated, and I upate it, but to no avail.

**Comment by dylang** [comment]
Sounds like a problem with `n`. What do you get for `npm config get prefix` and `which npm`? 

Are you able to switch to [nvm](https://github.com/creationix/nvm) instead?  `nvm` is bash script, not a node module, so it doesn't work in every OS. I recommend it because `n` shares the same global node modules directory across Node versions which can cause many unexpected issues. 

```
~ ❯ nvm use 4
Now using node v4.0.0 (npm v2.14.2)
~ ❯ npm --version
2.14.2
~ ❯ npm-check -g -u
? Choose which packages to update. npm  2.14.2  ❯  2.14.3  https://docs.npmjs.com/
Running npm install -g --color=always npm@2.14.3
/Users/dgreene/.nvm/versions/node/v4.0.0/bin/npm -> /Users/dgreene/.nvm/versions/node/v4.0.0/lib/node_modules/npm/bin/npm-cli.js
npm@2.14.3 /Users/dgreene/.nvm/versions/node/v4.0.0/lib/node_modules/npm

[npm-check] Update complete!
[npm-check] You should re-run your tests to make sure everything works with the updates.
previous command took 12s.
~ ❯ npm --version
2.14.3
```

**Comment by builtbylane** [comment]
```
❯ which node
/usr/local/bin/node

❯ npm config get prefix
/Users/[me]/.node

```

node is installed from homebrew

switching over to nvm today to see if that helps.
