### ISSUE TITLE
Finding unused deps based on a transpiled file

### ISSUE THREAD

**Issue by tnrich** [dylang/npm-check#52]
Hey there, 

I'm using JSX in my code which, to my understanding, messes with detective's ability to parse the require statements correctly and figure out what's used and what isn't.

I'm just wondering if there is an easy way to point npm-check at my webpack-bundled file (which contains no JSX), and have detective correctly parse that and tell me what's used/unused.

Thanks for the excellent tool!

**Comment by dylang** [comment]
`npm-check` doesn't use detective anymore because of that issue. It should work fine on the non-transpiled files that are using `import from` syntax. If you are seeing otherwise, can you share some code that exhibits the issue?

I'm not planning on supporting bundled files because it will be too difficult to figure out what dependencies were bundled in.

**Comment by tnrich** [comment]
It's actually jsx that is not being parsed correclty I believe
