### ISSUE TITLE
npm-check command not working

### ISSUE THREAD

**Issue by js08** [dylang/npm-check#55]
![screen shot 2015-10-22 at 7 48 40 pm](https://cloud.githubusercontent.com/assets/1699943/10682039/2490b6fc-78f6-11e5-8c8a-85c47de8fb58.png)

**Comment by dylang** [comment]
This is an issue with your node setup, not `npm-check`. At top it looks like you are getting a security error, probably because you don't have access to write to the location for installing node modules globally, and the second try installed `npm-check` locally, not globally, so `npm-check` on the command line won't work because it's not in your path.

**Comment by js08** [comment]
@dylang any idea how to make it work globally :(

**Comment by dylang** [comment]
Sorry @js08, you need some help with your Node setup, I can't provide that for you. Maybe try your coworkers/classmates or stack exchange.
