### ISSUE TITLE
File permission error in home directory

### ISSUE THREAD

**Issue by krzysieki** [dylang/npm-check#65]
Hi

My OS is Ubuntu 14.04LTS.

I installed nodejs using popular https://github.com/nodesource/distributions.
This means that I have to call all "npm ... -g" commands with sudo.
"npm-check -g" I call with sudo too.

Now I have problem that after calling "sudo npm-check -g -u" 
there is a file in my home folder:
~/.config/configstore/update-notifier-npm-check.json
with root ownership.

Next, calling "npm-check -u" in my home folder projects fails with:
"Error: EACCES: permission denied"

The hotfix is to call "sudo chown" on "~/.config/configstore/update-notifier-npm-check.json"
But the problem is annoying.

PS. Thanks for your work!

**Comment by dylang** [comment]
Hi @krzysieki, great issue.

This file is created by [update notifier](https://github.com/yeoman/update-notifier). I recommend posting an issue there.

> This means that I have to call all "npm ... -g" commands with sudo.

Are you able to change the ownership of the directory you use for global modules so you don't need to install with `sudo`? I personally never install with `sudo` because I don't know what the module install process might intentionally or accidently do my system.

An issue I saw that might be related to this: https://github.com/yeoman/update-notifier/issues/48

**Comment by krzysieki** [comment]
You are right. I will check but seems to be update notifier problem and not npm-check.

I've switched to NVM instead of package form nodesource apt-get repository.
With NVM everything works as expected :)

Thanks
